[package]
name = "local-vectored-llm"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
reqwest = { version = "0.11.24", features = ["json"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
clap = { version = "4.4.18", features = ["derive"] }
anyhow = "1.0.79"
thiserror = "1.0.56"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
pdf-extract = "0.7.3"
walkdir = "2.4.0"
futures = "0.3.30"
chromadb = "0.4.2"
ollama-rs = "0.1.6"

[[bin]]
name = "vectorize"
path = "src/bin/vectorize.rs"

[[bin]]
name = "query"
path = "src/bin/query.rs"

[lib]
name = "local_vectored_llm"
path = "src/lib.rs"
