[package]
name = "local-vectored-llm"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.45.0", features = ["full"] }
serde_json = "1.0.140"
clap = { version = "4.5.38", features = ["derive"] }
anyhow = "1.0.98"
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
pdf-extract = "0.9.0"
walkdir = "2.4.0"
futures = "0.3.30"
chromadb = "0.4.4"
ollama-rs = "0.1.9"

[[bin]]
name = "vectorize"
path = "src/bin/vectorize.rs"

[[bin]]
name = "query"
path = "src/bin/query.rs"

[lib]
name = "local_vectored_llm"
path = "src/lib.rs"
