FROM ollama/ollama:0.6.8

RUN /bin/ollama serve & sleep 5 && ollama run deepseek-r1:1.5b
# RUN /bin/ollama serve & sleep 5 && ollama run hf.co/mmnga/cyberagent-DeepSeek-R1-Distill-Qwen-14B-Japanese-gguf
